# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/biobert-bern',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/biobert-bern',
                'lib_path': 'biobert_bern'},
  'syms': { 'biobert_bern.biobertApi': { 'biobert_bern.biobertApi.create_text_block': ( 'biobertapi.html#create_text_block',
                                                                                        'biobert_bern/biobertApi.py'),
                                         'biobert_bern.biobertApi.get_comment_spans_textblock': ( 'biobertapi.html#get_comment_spans_textblock',
                                                                                                  'biobert_bern/biobertApi.py'),
                                         'biobert_bern.biobertApi.query_plain': ( 'biobertapi.html#query_plain',
                                                                                  'biobert_bern/biobertApi.py')},
            'biobert_bern.fmf_biobert': { 'biobert_bern.fmf_biobert.get_comment_spans_textblock': ( 'found_my_fitness_biobert_bern.html#get_comment_spans_textblock',
                                                                                                    'biobert_bern/fmf_biobert.py')}}}
