# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_biobertApi.ipynb.

# %% auto 0
__all__ = ['create_text_block']

# %% ../nbs/00_biobertApi.ipynb 1
import requests
import re
import pandas as pd

# %% ../nbs/00_biobertApi.ipynb 7
def create_text_block(df:pd.DataFrame, #pandas DataFrame containg a column, titled "comments," of text elements.  In this case these are Youtube comments.
                     ):
    '''This function takes a pandas DataFrame with a column titled "comments" that is filled with text strings, ie. from comments.  It adds an index number to each text string and adds '::' at the end for later parsing.  Finally, it returns all text elements combined into a single text block'''
    df.reset_index(inplace=True)
    df.rename(columns = {"index":"idx"},inplace=True)
    df.idx = df.idx.astype(str)
    df['comidx'] = df.idx +': '+df.comments+' ::'
    df.comidx = df.comidx.str.lower().str.replace(r'\(|\)',',',regex=True)
    return ' '.join(df.comidx.tolist())
